# Generated by Django 5.0.6 on 2024-06-11 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamescore',
            name='date',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='user',
        ),
        migrations.AddField(
            model_name='gamescore',
            name='player_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
